### ISSUE TITLE
Error with CPU frequency under WSL2

### ISSUE THREAD

**Issue by IndrekHaav** [wick3dr0se/fetch.sh#6]
Ubuntu 20.04 under WSL2, script throws an error when trying to find CPU frequency:

```
cpu ~ Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHzsort: cannot read: '/sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq': No such file or directory
 GHz
```

Looks like the required files don't exist:

```shell
~$ ls -l /sys/devices/system/cpu/cpu0/
total 0
drwxr-xr-x 6 root root    0 Nov 22 11:28 cache
lrwxrwxrwx 1 root root    0 Nov 22 11:28 driver -> ../../../../bus/cpu/drivers/processor
lrwxrwxrwx 1 root root    0 Nov 22 11:28 firmware_node -> ../../../LNXSYSTM:00/ACPI0007:00
drwxr-xr-x 2 root root    0 Nov 22 11:28 hotplug
lrwxrwxrwx 1 root root    0 Nov 22 11:28 subsystem -> ../../../../bus/cpu
drwxr-xr-x 2 root root    0 Nov 22 11:28 topology
-rw-r--r-- 1 root root 4096 Nov 22 11:28 uevent
```

**Comment by wick3dr0se** [comment]
Can you check this with the latest commit? I added an if statement for part of the path but I may have to do something entirely different if /sys/devices/system/cpu shows up but /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq doesn't

**Comment by IndrekHaav** [comment]
Yeah, no error anymore, but there's no space between the CPU model and the next label:

```
cpu ~ Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHzpkgs ~ 760
```

**Comment by wick3dr0se** [comment]
Can you check new commit?

**Comment by IndrekHaav** [comment]
```
cpu ~ Intel Core i7-1065G7  @ 1.30GHzgpu ~ pkgs ~ 760
```

This only happens if CPU frequency is not found.

**Comment by wick3dr0se** [comment]
Run latest commit and let me know if any error persist

**Comment by SaintFenix** [comment]
I'm currently getting this output on Ubuntu 20.04 WSL2:

```
fenix@FenixesComputer
kernel ~ 5.10.60.1-microsoft-standard-WSL2
uptime ~ 2 minutes
os ~ Ubuntu 20.04.3 LTS arch ~ x86_64
de/wm ~  theme ~ 'Adwaita'
cpu ~ AMD Ryzen 7 3700X 8-Core cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory
cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory


gpu ~ 0000 SCSI storage controller Red Hat, Inc Virtio filesystem (rev 01)
0000 SCSI storage controller Red Hat, Inc Virtio filesystem (rev 01)
0000 3D controller Microsoft  Device 008e
0000 SCSI storage controller Red Hat, Inc Virtio filesystem (rev 01)
pkgs ~ 629
ram ~ 64274 MiB./fetch.sh: line 141: let: swap_mb =  / 1024: syntax error: operand expected (error token is "/ 1024")
 swap ~  MiB
term ~ init shell ~ zsh
```

The two new lines after CPU are untouched from my output as well.

**Comment by wick3dr0se** [comment]
Commit 636fe7bcbfea725a3af6dbc34e5c836025834083 should have fixed this issue by looking for the full path or hiding the speed all together

**Comment by SaintFenix** [comment]
With the latest revision I'm getting this instead:

```
fenix@FenixesComputer
kernel ~ 5.10.60.1-microsoft-standard-WSL2
uptime ~ 1 hour, 32 minutes
os ~ Ubuntu 20.04.3 LTS arch ~ x86_64
de/wm ~  theme ~ 'Adwaita'
cpu ~ AMD Ryzen 7 3700X 8-Core cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory
cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory


avgs ~ 0.00 0.00 0.00
gpu ~ 0000 SCSI storage controller Red Hat, Inc Virtio filesystem (rev 01)
0000 SCSI storage controller Red Hat, Inc Virtio filesystem (rev 01)
0000 3D controller Microsoft  Device 008e
0000 SCSI storage controller Red Hat, Inc Virtio filesystem (rev 01)
pkgs ~ 629
ram ~ 64274 MiB swap ~ 16384 MiB
term ~ init shell ~ zsh
```

RAM is reading properly now, still getting the issue with the cpu.

Appreciate your work on it. :)

**Comment by wick3dr0se** [comment]
Commit 854c65512d57cee45b5511436c4e41969494d447 should fix it

**Comment by IndrekHaav** [comment]
Still broken:

```
cpu ~ Intel Core i7-1065G7   1.30GHzcat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory
cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory
GHz@
```

**Comment by wick3dr0se** [comment]
Commit e6b760965761922fa68488c484a08e48777a045d possible solution? I think because it's a symbolic link it shows not found on some systems? I changed method to test -e to search for sym links

**Comment by SaintFenix** [comment]
I'm still receiving the same as @IndrekHaav , even on commit e6b7609

```
cpu ~ AMD Ryzen 7 3700X 8-Core head: cannot open '/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq' for reading: No such file or directory
head: cannot open '/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq' for reading: No such file or directory
```

I'll see if I can take a stab at it too, since I can iterate on it pretty quick.

**Comment by SaintFenix** [comment]
Here's an image of the /sys/devices/system/cpu/cpu0 directory on my side, so we can see that there seems to be no further detail here to pull data from.
![image](https://user-images.githubusercontent.com/29680981/143047150-7ac8d53c-5e9f-4088-8470-9f046941d9b2.png)

This is interesting, I've never dug into this on the WSL2 side before.

**Comment by wick3dr0se** [comment]
```
max_cpu=$(head /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq | sed 's/......$/.&/;s/....$//' | tr -d '\n')
scal_cpu=$(head /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq | sed 's/......$/.&/;s/.....$//' | tr -d '\n')
if [[ -e /sys/devices/system/cpu/cpu0/cpufreq ]] ; then
    echo symlink found
    echo -ne "${CYAN}$max_cpu${NC}"
    echo -ne "@${YELLOW}$scal_cpu${NC}" ; echo GHz
else
    echo symlink not found
fi
```
I tested this works by creating a symlink directory and it print symlink found then I del the directory it prints symlink not found. Should work for you...

**Comment by wick3dr0se** [comment]
@SimoneSalzano 's potential fix commit 451e47b68faaa0515dfc25e0cef3cb254973005b

**Comment by SaintFenix** [comment]
With the current build, I don't get a Ghz at all, which looks fine admittedly:

![image](https://user-images.githubusercontent.com/29680981/143156290-c80ae9f9-69ac-4b0e-973e-eb91fa34bd51.png)

The Current theme issue referenced in #37 is also shown here.

**Comment by wick3dr0se** [comment]
Closing as solved. If issue persist, please open a new issue.
